### PR TITLE
fix: proper gtk-icon-sizes string

### PR DESCRIPTION
**Pull request by Kermit**
Fix for #50. I believe it's more workaround than fix but maybe it will be helpful.

### CODE REVIEW

**Comment by yuyichao** [comment]
I don't think this is the right fix or workaround.
The problem seems to be an previous argument being empty.

What is the output of your `kde4-config --expandvars --install icon` ?

**Comment by Kermit** [comment]
I don't any part of KDE installed so I can't run kde4-config. I'm using RazorQt/LXDE-Qt -> it's clean Qt environment.

**Comment by yuyichao** [comment]
OK, then that is indeed the reason.
Can you try the current master?

**Comment by Kermit** [comment]
After yours changes everything works like a charm. Thanks!

**Pull request closed without merging**
