### PR TITLE
Fix some localization issues

### PR DESCRIPTION
**Pull request by Pulfer**
1. Add missing Russian translation to Qt4 theme description
2. Use single quotes to avoid localization issues and keep quoted strings style consistent

### CODE REVIEW

**Comment by yuyichao** [comment]
Second commit merged (although it will be unnecessary).
For the first commit, I assume you mean the `&quot;` in the `*.po`/`*.pot` files. I don't think this is the right way to fix the problem (the translation part will be completely rewriten for sure) and I don't see how this make quoted string style consistent (since there are still a lot of both single and double quote).

**Comment by Pulfer** [comment]
I see. Just pushed patches that fix things in ROSA & OpenMandriva. It's fine for me to keep rejected patches in SRPM.

**Comment by yuyichao** [comment]
The rewrite of this part should be done by the next release and you are welcome to check if there is still any poblem at that time.

**Comment by Pulfer** [comment]
Surely :-)

**Pull request closed without merging**
